import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoadingScreen from "@/components/LoadingScreen";
import Navbar from "@/components/Navbar";
import FullPageScroll from "@/components/FullPageScroll";
import ClientWrapper from "@/components/ClientWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HiooDev - Full-Stack Developer Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet" />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth overflow-x-hidden`}>
        <ClientWrapper>
          <div className="min-h-screen flex flex-col">
            <Navbar />
            <main className="flex-1 overflow-y-auto snap-y snap-mandatory">
              <LoadingScreen duration={3000}>{children}</LoadingScreen>
            </main>
          </div>
        </ClientWrapper>
      </body>
    </html>
  );
}
