import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import LoadingScreen from "@/components/LoadingScreen";
import Navbar from "@/components/Navbar";
import FullPageScroll from "@/components/FullPageScroll";
import ClientWrapper from "@/components/ClientWrapper";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "HiooDev - Full-Stack Developer Portfolio",
  description: "Generated by create next app",
  other: {
    'preconnect': 'https://fonts.googleapis.com',
    'preconnect-crossorigin': 'https://fonts.gstatic.com',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased scroll-smooth overflow-x-hidden`} style={{ fontFamily: 'Poppins, sans-serif' }}>
        <ClientWrapper>
          <div className="min-h-screen flex flex-col">
            <Navbar />
            <main className="flex-1 overflow-y-auto snap-y snap-mandatory">
              <LoadingScreen duration={3000}>{children}</LoadingScreen>
            </main>
          </div>
        </ClientWrapper>
      </body>
    </html>
  );
}
